-- AlterEnum
ALTER TYPE "Pocket" ADD VALUE 'CORNER_YELLOW';
ALTER TYPE "Pocket" ADD VALUE 'CORNER_GREEN';
ALTER TYPE "Pocket" ADD VALUE 'MIDDLE_YELLOW';
ALTER TYPE "Pocket" ADD VALUE 'MIDDLE_GREEN';
ALTER TYPE "Pocket" ADD VALUE 'CORNER_BLACK_YELLOW';
ALTER TYPE "Pocket" ADD VALUE 'CORNER_BLACK_GREEN';
